# Generated by Django 4.2.1 on 2023-05-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='tour_image/')),
                ('title_desc', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=555)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_bg', models.FileField(upload_to='bg/')),
                ('footer_bg', models.FileField(upload_to='bg/')),
                ('email_bg', models.FileField(upload_to='bg/')),
                ('trips', models.CharField(max_length=25)),
                ('tourists', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('price', models.CharField(max_length=255)),
                ('days', models.CharField(max_length=255)),
                ('bg_image', models.ImageField(upload_to='bg/')),
            ],
        ),
    ]
