# Generated by Django 4.2.1 on 2023-05-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='gallery')),
            ],
        ),
        migrations.AddField(
            model_name='tours',
            name='price1',
            field=models.CharField(default=1, max_length=25, verbose_name='Цена на 1 человека'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='price2',
            field=models.CharField(default=1, max_length=25, verbose_name='Цена на 2 человека'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='price3',
            field=models.CharField(default=1, max_length=25, verbose_name='Цена на 3 человека'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='price4',
            field=models.CharField(default=1, max_length=25, verbose_name='Цена на 4 человека'),
            preserve_default=False,
        ),
    ]
