# Generated by Django 4.2.1 on 2023-05-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_photo_video_tours_price1_tours_price2_tours_price3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='gallery_vid1',
            field=models.FileField(default=1, upload_to='gallery/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='gallery_vid2',
            field=models.FileField(default=1, upload_to='gallery/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='gallery_vid3',
            field=models.FileField(default=1, upload_to='gallery/'),
            preserve_default=False,
        ),
    ]
