# Generated by Django 4.2.1 on 2023-05-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_setting_gallery_vid1_setting_gallery_vid2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='gallery_bg',
            field=models.FileField(default=1, upload_to='bg/'),
            preserve_default=False,
        ),
    ]
