# Generated by Django 4.2.1 on 2023-05-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_setting_gallery_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='included',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='not_included',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
