# Generated by Django 4.2.1 on 2023-06-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_days_options_alter_photo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tours',
            name='days',
            field=models.CharField(max_length=2555),
        ),
        migrations.AlterField(
            model_name='tours',
            name='price',
            field=models.CharField(max_length=2555),
        ),
        migrations.AlterField(
            model_name='tours',
            name='title',
            field=models.CharField(max_length=2555),
        ),
    ]
